### ISSUE TITLE
Error 1 in example notebook, but only on the first pass

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/dataportal#11]
When I try to run http://nbviewer.ipython.org/gist/danielballan/ec934485d42f0b524fea, I get the following error when I run cell [31]

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-25b06378a33a> in <module>()
     11                            'external': 'FILESTORE'}})
     12     # Make file descriptor entry.
---> 13     fb = fs.commands.save_file_base(file_types[n%len(file_types)], 'filepath',
     14                            {'shape': shape})
     15     for m in range(M):

AttributeError: 'module' object has no attribute 'save_file_base'
```

I'm working on master branches of 
- databroker
- fileStore
- channelarchiver

Oddly, this error only appears the first time I run through the notebook after restarting the kernel.  If I run it again from the top without restarting the kernel, this error does not appear

**Comment by tacaswell** [comment]
This should be fixed now, the branch that had this code is now merged (https://github.com/NSLS-II/fileStore/pull/6)

**Comment by tacaswell** [comment]
Change 

``` python
# aliases for brevity
mds = sources.metadataStore
fs = sources.fileStore

# Switch to dummy versions of all sources. The API is unchanged.
sources.switch(metadatastore=False, filestore=True, channelarchiver=False)
```

to 

``` python
# Switch to dummy versions of all sources. The API is unchanged.
sources.switch(metadatastore=False, filestore=True, channelarchiver=False)

# aliases for brevity
mds = sources.metadataStore
fs = sources.fileStore


```

**Comment by danielballan** [comment]
Revised example: http://nbviewer.ipython.org/gist/danielballan/a74b11aa662cd9f035bb

@ericdill please close this issue if you can run it successfully.

**Comment by ericdill** [comment]
This problem no longer occurs, however #12 is still present... what am i doing wrong?
